type Album {
  id: Int!
  cover: String
  title: String!
  release_year: Int
  artist: Artist
  artist_id: Int
  songs: [Song]
}

input AlbumCreateInput {
  title: String!
  cover: String
  songIds: [Int!]!
  release_year: Int
  artist_id: Int!
}

input AlbumUpdateInput {
  title: String
  cover: String
  songIds: [Int]
  release_year: Int
  artist_id: Int
}
