type Album {
  artist: Artist!
  artist_id: Int
  cover: String
  id: Int!
  release_year: Int
  songs: [Song]
  title: String!
}

input AlbumCreateInput {
  # WIP - Intégrer au context header
  # artist_id: Int!
  cover: String
  release_year: Int
  songIds: [Int!]!
  title: String!
}

input AlbumUpdateInput {
  artist_id: Int
  cover: String
  release_year: Int
  songIds: [Int]
  title: String
}

enum ReleaseYear {
  YEAR_70
  YEAR_80
  YEAR_90
  YEAR_2000
  YEAR_2010
}

input AlbumFilterInput {
  release_year: ReleaseYear
}