type Artist {
  id: Int!
  email: String
  name: String!
  country: String
  albums: [Album]
}

type JWT {
  token: String
  expire_at: String
}

input LoginInput {
  email: String!
  password: String!
}
