type Artist {
  id: Int!
  # email row exists in table but is visible only to the artist himself
  # email: String
  name: String!
  country: String
  albums: [Album]
}

type ArtistUser {
  email: String!
  name: String!
  country: String
  albums: [Album]
}

type JWT {
  token: String
  expire_at: String
}

input LoginInput {
  email: String!
  password: String!
}
