type Mutation {
  # -- Create -- #
  addAlbum(input: AlbumCreateInput!): Album
  addSong(input: SongCreateInput!): Song
  addArtist(input: ArtistCreateInput!): Artist

  # -- Update -- #
  updateAlbum(albumId: Int!, albumArtistId: Int!, input: AlbumUpdateInput!): Album
  updateArtist(input: ArtistUpdateInput!): Artist
  updateSong(songId: Int!, input: SongUpdateInput!): Song

  # -- Delete -- #
  deleteAlbum(id: Int!): Boolean
  deleteArtist: Boolean
  deleteSongs(ids: [Int!]!): Boolean

  # -- Others -- #
  likeSong(id: Int!): Boolean
  unlikeSong(id: Int!): Boolean
}
 