type Mutation {
  addAlbum(input: AlbumCreateInput!): Album
  # Même si aucun champ n'est obligatoire dans le update, on force l'utilisateur à modifier quelque chose au minimum
  updateAlbum(id: Int!, input: AlbumUpdateInput!): Album
  #! It must force auth check before delete
  deleteAlbum(id: Int!): Boolean
  # We must be connected (JWT check) to update his profile
  updateArtist(input: ArtistUpdateInput!): Artist
  addSong(input: SongCreateInput!): Song
  # It will delete his song and his album before
  deleteArtist(id: Int!): Boolean
  deleteSongs(ids: [Int!]!): Boolean
  likeSong(id: Int!): Boolean
  unlikeSong(id: Int!): Boolean
}
