type Artist {
  id: Int!
  name: String!
  country: String
  albums: [Album]
}

type Album {
  id: Int!
  title: String!
  release_year: Int
  artist: Artist
  artist_id: Int
}

type Song {
  id: Int!
  "Title of the song"
  title: String!
  "Duration in seconds of the song"
  duration: Int!
  "The Lyrics, if there is in"
  lyrics: String
  album_id: Int!
}

type Query {
  albums: [Album]
  album(id: Int!): Album
  songs: [Song]
  song(id: Int!): Song
}

input AlbumCreateInput {
  title: String!
  release_year: Int
  artist_id: Int
}

input AlbumUpdateInput {
  title: String
  release_year: Int
  artist_id: Int
}

type Mutation {
  addAlbum(input: AlbumCreateInput!): Album
  # Même si aucun champ n'est obligatoire dans le update, on force l'utilisateur à modifier quelque chose au minimum
  updateAlbum(id: Int!, input: AlbumUpdateInput!): Album
  deleteAlbum(id: Int!): Boolean
}