type Song {
  artist: Artist
  cover: String
  "Duration in second"
  duration: Int!
  id: Int!
  lyrics: String
  songOnAlbum: [SongOnAlbum]
  like: [ArtistLikeSong]
  nbLike: Int
  title: String!
}

input SongCreateInput {
  artistId: Int!
  cover: String
  duration: Int!
  lyrics: String
  title: String!
}
