type Song {
  id: Int!
  title: String!
  "Duration in second"
  duration: Int!
  cover: String
  lyrics: String
  artist: Artist!
}

input SongCreateInput {
  title: String!
  cover: String
  duration: Int!
  lyrics: String
  artistId: Int!
}
