type Song {
  artist: Artist
  cover: String
  "Duration in second"
  duration: Int!
  id: Int!
  lyrics: String
  songOnAlbum: [SongOnAlbum]
  like: [ArtistLikeSong]
  nbLike: Int
  title: String!
  date: String
}

input SongCreateInput {
  artistId: Int!
  cover: String
  duration: Int!
  lyrics: String
  title: String!
}

enum DurationRange {
  ONE_MINUTE
  ONE_TO_THREE_MINUTES
  THREE_TO_FIVE_MINUTES
  MORE_THAN_FIVE_MINUTES
}

enum Year {
  YEAR_70
  YEAR_80
  YEAR_90
  YEAR_2000
  YEAR_2010
}

input SongFilterInput {
  durationFilter: DurationRange
  yearFilter: Year
}
